name: release

on:
  push:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    needs: 
      - goreleaser
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Generate a changelog
        uses: orhun/git-cliff-action@f50e11560dce63f7c33227798f90b924471a88b5 # v4
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: docs/CHANGELOG.md
      
      - name: Commit files
        id: commit
        run: |
          if git diff --quiet; then
            echo "No changes to commit."
            echo "hasdiff=false" >> "$GITHUB_OUTPUT"
          else
            echo "Changes detected."
            echo "hasdiff=true" >> "$GITHUB_OUTPUT"
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add docs/CHANGELOG.md
            git commit -m "chore(docs): update changelog"
          fi
      - name: Push changes
        if: ${{ steps.commit.outputs.hasdiff == 'true' }}
        uses: ad-m/github-push-action@881a6320fdb16eb5318c5054f31c218aec2b324c # v1.3.0
        with:
          github_token: ${{ secrets.CHANGELOG_GITHUB_TOKEN }}
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version: '1.26'
      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7
        with:
          install-only: true
      - name: Show GoReleaser version
        run: goreleaser -v
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@b12c8f6015dc215fe37bc154d4ad456dd3833c90 # v6.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.CHANGELOG_GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.CHANGELOG_GITHUB_TOKEN }}
        with:
          extra_plugins: |
            @semantic-release/git
            @semantic-release/exec